import { NgModule } from '@angular/core';
import {
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatDatepickerModule,
    MatDialogModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatNativeDateModule,
    MatProgressBarModule,
    MatRadioModule,
    MatSelectModule,
    MatCheckboxModule,
    MatSlideToggleModule,
    MatTableModule,
    MatTooltipModule,
    MatAutocompleteModule,
    MatTabsModule,
    MatToolbarModule,
    MatSidenavModule
} from '@angular/material';

@NgModule({
    imports: [
        MatButtonModule,
        MatButtonToggleModule,
        MatCardModule,
        MatDatepickerModule,
        MatDialogModule,
        MatExpansionModule,
        MatFormFieldModule,
        MatIconModule,
        MatInputModule,
        MatListModule,
        MatNativeDateModule,
        MatProgressBarModule,
        MatRadioModule,
        MatSelectModule,
        MatCheckboxModule,
        MatSlideToggleModule,
        MatTableModule,
        MatTooltipModule,
        MatAutocompleteModule,
        MatTabsModule,
        MatToolbarModule,
        MatSidenavModule
    ],
    exports: [
        MatButtonModule,
        MatButtonToggleModule,
        MatCardModule,
        MatDatepickerModule,
        MatDialogModule,
        MatExpansionModule,
        MatFormFieldModule,
        MatIconModule,
        MatInputModule,
        MatListModule,
        MatNativeDateModule,
        MatProgressBarModule,
        MatRadioModule,
        MatSelectModule,
        MatCheckboxModule,
        MatSlideToggleModule,
        MatTableModule,
        MatTooltipModule,
        MatAutocompleteModule,
        MatTabsModule,
        MatToolbarModule,
        MatSidenavModule
    ]
})
export class MaterialModule { }
